n1 = int(input('Ingresa primer numero: '))
n2 = int(input('Ingresa segundo numero: '))
n3 = int(input('Ingresa tercero numero: '))
n4 = int(input('Ingresa cuarto numero: '))
n5 = int(input('Ingresa quinto numero: '))
mayor = max(n1, n2, n3, n4, n5)
menor = min(n1, n2, n3, n4, n5)
print('El numero mayor es: {}' .format(mayor))
print('El numero menor es: {}' .format(menor))
